from __future__ import annotations

import configparser
from pathlib import Path

import pytest


def read_theme_name(theme_dir: Path) -> str | None:
    for filename in ("index.theme", "cursor.theme"):
        f = theme_dir / filename
        if not f.is_file():
            continue
        parser = configparser.RawConfigParser()
        parser.read(f, encoding="utf-8")
        for section in ("Icon Theme", "Cursor Theme"):
            if parser.has_section(section):
                name = parser.get(section, "Name", fallback=None)
                if name and name.strip():
                    return name.strip()
    return None


def write_output_metadata(
    theme_dir: Path,
    display_name: str,
    source_name: str,
    original_dir: Path | None = None,
) -> None:
    cfg = configparser.RawConfigParser()
    index = theme_dir / "index.theme"

    if index.is_file():
        cfg.read(index, encoding="utf-8")

    if not cfg.has_section("Icon Theme"):
        cfg["Icon Theme"] = {}

    cfg["Icon Theme"]["Name"] = display_name
    cfg["Icon Theme"]["Comment"] = "Generated by CursorForge with additional cursor sizes"
    if source_name:
        cfg["Icon Theme"]["Inherits"] = source_name

    with index.open("w", encoding="utf-8") as fh:
        cfg.write(fh)


def is_safe_output_name(name: str) -> bool:
    return bool(name) and "/" not in name and "\\" not in name


class TestMetadata:
    def test_read_existing_index_theme(self, tmp_path: Path) -> None:
        cfg = configparser.RawConfigParser()
        cfg["Icon Theme"] = {"Name": "My Theme"}
        with (tmp_path / "index.theme").open("w") as f:
            cfg.write(f)
        assert read_theme_name(tmp_path) == "My Theme"

    def test_missing_index_returns_none(self, tmp_path: Path) -> None:
        assert read_theme_name(tmp_path) is None

    def test_preserves_unrelated_keys(self, tmp_path: Path) -> None:
        cfg = configparser.RawConfigParser()
        cfg["Icon Theme"] = {"Name": "Old", "Example": "preserved_value"}
        with (tmp_path / "index.theme").open("w") as f:
            cfg.write(f)

        write_output_metadata(tmp_path, "New Name", "OldTheme")

        out = configparser.RawConfigParser()
        out.read(tmp_path / "index.theme", encoding="utf-8")
        assert out.get("Icon Theme", "Example") == "preserved_value"

    def test_updates_display_name(self, tmp_path: Path) -> None:
        write_output_metadata(tmp_path, "Generated Theme", "SourceTheme")
        out = configparser.RawConfigParser()
        out.read(tmp_path / "index.theme", encoding="utf-8")
        assert out.get("Icon Theme", "Name") == "Generated Theme"

    def test_safe_output_name_valid(self) -> None:
        assert is_safe_output_name("MyTheme-Multi")

    def test_safe_output_name_rejects_slash(self) -> None:
        assert not is_safe_output_name("bad/name")

    def test_safe_output_name_rejects_empty(self) -> None:
        assert not is_safe_output_name("")

    def test_creates_index_when_missing(self, tmp_path: Path) -> None:
        write_output_metadata(tmp_path, "Brand New", "Source")
        assert (tmp_path / "index.theme").is_file()
