from __future__ import annotations

import configparser
from pathlib import Path


def read_theme_name(theme_dir: Path) -> str | None:
    """Read the display name from index.theme or cursor.theme, or return None."""
    for filename in ("index.theme", "cursor.theme"):
        f = theme_dir / filename
        if not f.is_file():
            continue
        parser = configparser.RawConfigParser()
        parser.read(f, encoding="utf-8")
        for section in ("Icon Theme", "Cursor Theme"):
            if parser.has_section(section):
                name = parser.get(section, "Name", fallback=None)
                if name and name.strip():
                    return name.strip()
    return None


def write_output_metadata(
    theme_dir: Path,
    display_name: str,
    source_name: str,
    original_dir: Path | None = None,
) -> None:
    """Write (or update) index.theme in theme_dir with CursorForge metadata."""
    cfg = configparser.RawConfigParser()
    index = theme_dir / "index.theme"

    if index.is_file():
        cfg.read(index, encoding="utf-8")

    if not cfg.has_section("Icon Theme"):
        cfg["Icon Theme"] = {}

    cfg["Icon Theme"]["Name"] = display_name
    cfg["Icon Theme"]["Comment"] = "Generated by CursorForge with additional cursor sizes"
    if source_name:
        cfg["Icon Theme"]["Inherits"] = source_name

    theme_dir.mkdir(parents=True, exist_ok=True)
    with index.open("w", encoding="utf-8") as fh:
        cfg.write(fh)


def is_safe_output_name(name: str) -> bool:
    """Return True if name is a valid, non-path theme directory name."""
    return bool(name) and "/" not in name and "\\" not in name
